(function(d,f){"object"===typeof window&&(window[d]=f())})("Ribbons",function(){var d=window,f=document.body,c=document.documentElement,m=function(){if(1===arguments.length){if(Array.isArray(arguments[0])){var a=Math.round(m(0,arguments[0].length-1));return arguments[0][a]}return m(0,arguments[0])}return 2===arguments.length?Math.random()*(arguments[1]-arguments[0])+arguments[0]:0},n=function(a){a=Math.max(0,d.innerWidth||c.clientWidth||f.clientWidth||0);var b=Math.max(0,d.innerHeight||c.clientHeight||
f.clientHeight||0);return{width:a,height:b,ratio:a/b,centerx:a/2,centery:b/2,scrollx:Math.max(0,d.pageXOffset||c.scrollLeft||f.scrollLeft||0)-(c.clientLeft||0),scrolly:Math.max(0,d.pageYOffset||c.scrollTop||f.scrollTop||0)-(c.clientTop||0)}},g=function(a,b){this.y=this.x=0;this.set(a,b)};g.prototype={constructor:g,set:function(a,b){this.x=a||0;this.y=b||0},copy:function(a){this.x=a.x||0;this.y=a.y||0;return this},multiply:function(a,b){this.x*=a||1;this.y*=b||1;return this},divide:function(a,b){this.x/=
a||1;this.y/=b||1;return this},add:function(a,b){this.x+=a||0;this.y+=b||0;return this},subtract:function(a,b){this.x-=a||0;this.y-=b||0;return this},clampX:function(a,b){this.x=Math.max(a,Math.min(this.x,b));return this},clampY:function(a,b){this.y=Math.max(a,Math.min(this.y,b));return this},flipX:function(){this.x*=-1;return this},flipY:function(){this.y*=-1;return this}};var k=function(a){this._sto=this._context=this._canvas=null;this._scroll=this._height=this._width=0;this._ribbons=[];this._options=
{colorSaturation:"80%",colorBrightness:"60%",colorAlpha:.65,colorCycleSpeed:6,verticalPosition:"center",horizontalSpeed:150,ribbonCount:5,strokeSize:5,parallaxAmount:-.5,animateSections:!0};this._onDraw=this._onDraw.bind(this);this._onResize=this._onResize.bind(this);this._onScroll=this._onScroll.bind(this);this.setOptions(a);this.init()};k.prototype={constructor:k,setOptions:function(a){if("object"===typeof a)for(var b in a)a.hasOwnProperty(b)&&(this._options[b]=a[b])},init:function(){try{this._canvas=
document.createElement("canvas"),this._canvas.style.display="block",this._canvas.style.position="fixed",this._canvas.style.margin="0",this._canvas.style.padding="0",this._canvas.style.border="0",this._canvas.style.outline="0",this._canvas.style.left="0",this._canvas.style.top="0",this._canvas.style.width="100%",this._canvas.style.height="100%",this._canvas.style["z-index"]="-1",this._onResize(),this._context=this._canvas.getContext("2d"),this._context.clearRect(0,0,this._width,this._height),this._context.globalAlpha=
this._options.colorAlpha,window.addEventListener("resize",this._onResize),window.addEventListener("scroll",this._onScroll),document.body.appendChild(this._canvas)}catch(a){console.warn("Canvas Context Error: "+a.toString());return}this._onDraw()},addRibbon:function(){var a=5<Math.round(m(1,9))?"right":"left",b=1E3,d=this._width+200;var p="right"===a?-200:d;var e=Math.round(m(0,this._height));/^(top|min)$/i.test(this._options.verticalPosition)?e=200:/^(middle|center)$/i.test(this._options.verticalPosition)?
e=this._height/2:/^(bottom|max)$/i.test(this._options.verticalPosition)&&(e=this._height-200);for(var f=[],c=new g(p,e),h=new g(p,e),l,k=Math.round(m(0,360)),n=0;!(0>=b);){b--;p=Math.round((1*Math.random()-.2)*this._options.horizontalSpeed);e=Math.round(.25*(1*Math.random()-.5)*this._height);l=new g;l.copy(h);if("right"===a){if(l.add(p,e),h.x>=d)break}else if("left"===a&&(l.subtract(p,e),-200>=h.x))break;f.push({point1:new g(c.x,c.y),point2:new g(h.x,h.y),point3:l,color:k,delay:n,dir:a,alpha:0,phase:0});
c.copy(h);h.copy(l);n+=4;k+=this._options.colorCycleSpeed}this._ribbons.push(f)},_drawRibbonSection:function(a){if(a){if(1<=a.phase&&0>=a.alpha)return!0;if(0>=a.delay){if(a.phase+=.02,a.alpha=1*Math.sin(a.phase),a.alpha=0>=a.alpha?0:a.alpha,a.alpha=1<=a.alpha?1:a.alpha,this._options.animateSections){var b=.1*Math.sin(1+a.phase*Math.PI/2);"right"===a.dir?(a.point1.add(b,0),a.point2.add(b,0),a.point3.add(b,0)):(a.point1.subtract(b,0),a.point2.subtract(b,0),a.point3.subtract(b,0));a.point1.add(0,b);
a.point2.add(0,b);a.point3.add(0,b)}}else a.delay-=.5;b="hsla("+a.color+", "+this._options.colorSaturation+", "+this._options.colorBrightness+", "+a.alpha+" )";this._context.save();0!==this._options.parallaxAmount&&this._context.translate(0,this._scroll*this._options.parallaxAmount);this._context.beginPath();this._context.moveTo(a.point1.x,a.point1.y);this._context.lineTo(a.point2.x,a.point2.y);this._context.lineTo(a.point3.x,a.point3.y);this._context.fillStyle=b;this._context.fill();0<this._options.strokeSize&&
(this._context.lineWidth=this._options.strokeSize,this._context.strokeStyle=b,this._context.lineCap="round",this._context.stroke());this._context.restore()}return!1},_onDraw:function(){for(var a=0,b=this._ribbons.length;a<b;++a)this._ribbons[a]||this._ribbons.splice(a,1);this._context.clearRect(0,0,this._width,this._height);for(a=0;a<this._ribbons.length;++a){b=this._ribbons[a];for(var c=b.length,d=0,e=0;e<c;++e)this._drawRibbonSection(b[e])&&d++;d>=c&&(this._ribbons[a]=null)}this._ribbons.length<
this._options.ribbonCount&&this.addRibbon();requestAnimationFrame(this._onDraw)},_onResize:function(a){a=n(a);this._width=a.width;this._height=a.height;this._canvas&&(this._canvas.width=this._width,this._canvas.height=this._height,this._context&&(this._context.globalAlpha=this._options.colorAlpha))},_onScroll:function(a){this._scroll=n(a).scrolly}};return k});var cn=document.getElementById("ribbon_piao"),mb=cn.getAttribute("mobile");
"false"==mb&&/Android|webOS|iPhone|iPod|iPad|BlackBerry/i.test(navigator.userAgent)||new Ribbons({colorSaturation:"60%",colorBrightness:"50%",colorAlpha:.5,colorCycleSpeed:5,verticalPosition:"random",horizontalSpeed:200,ribbonCount:3,strokeSize:0,parallaxAmount:-.2,animateSections:!0});